[project]
name = "lettuce-ui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lettuce",
    "marimo>=0.16.5",
    "polars>=1.34.0",
    "ruff>=0.14.0",
]

[tool.uv.sources]
lettuce = { workspace = true }

